### 환경 설정 ###
### PREFERENCES ###

# 폰트
FONT: 'NanumSquareEB.ttf'
FONT_WIDTH: 16
FONT_HEIGHT: 16

# 언어
LANGUAGE: "ko"

# 색상 팔레트
COLORS:
  dark_wall: [0, 0, 100]
  dark_ground: [50, 50, 150]
  light_wall: [50, 50, 30]
  light_ground: [60, 60, 40]
  pitch_black: [0,0,0]
  ambient_light : -30
  explosion: [255, 52, 20]
  flash : [74, 177, 255]

# 화면 크기
SCREEN_WIDTH: 42
SCREEN_HEIGHT: 35

### 게임 기본 설정 ###
### GAME SETTINGS ###

# 지도
MAP_WIDTH: 35
MAP_HEIGHT: 25

# 인터페이스

# 체력 바
BAR_WIDTH: 20